# app/utils/exporters.py
"""
Multi-Format Export Module
Exports SOC reports and findings to: PDF, HTML, JSON, CSV, Markdown, Excel
Provides professional formatting for stakeholder distribution
"""

import json
import csv
import io
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional, Union
import pandas as pd
import base64

# Import config
import sys
sys.path.append(str(Path(__file__).parent.parent))
from config import REPORTS_DIR, APP_NAME, APP_VERSION

# Try importing optional dependencies
try:
    from jinja2 import Template
    JINJA_AVAILABLE = True
except ImportError:
    JINJA_AVAILABLE = False

try:
    from weasyprint import HTML
    WEASYPRINT_AVAILABLE = True
except ImportError:
    WEASYPRINT_AVAILABLE = False

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    OPENPYXL_AVAILABLE = True
except ImportError:
    OPENPYXL_AVAILABLE = False


class ReportExporter:
    """
    Multi-format report exporter for SOC findings
    Supports: PDF, HTML, JSON, CSV, Markdown, Excel
    """
    
    def __init__(self, company_name: str = "Security Operations Center"):
        self.company_name = company_name
        self.export_dir = REPORTS_DIR / f"exports_{datetime.now().strftime('%Y%m%d')}"
        self.export_dir.mkdir(parents=True, exist_ok=True)
        
    def export_json(self, data: Dict[str, Any], filename: str = None) -> str:
        """
        Export data to JSON format
        
        Args:
            data: Dictionary data to export
            filename: Optional filename (auto-generated if not provided)
            
        Returns:
            Path to exported file
        """
        if filename is None:
            filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        
        filepath = self.export_dir / filename
        
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2, default=str)
        
        return str(filepath)
    
    def export_csv(self, df: pd.DataFrame, filename: str = None) -> str:
        """
        Export DataFrame to CSV
        
        Args:
            df: Pandas DataFrame
            filename: Optional filename
            
        Returns:
            Path to exported file
        """
        if filename is None:
            filename = f"data_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        
        filepath = self.export_dir / filename
        df.to_csv(filepath, index=False)
        
        return str(filepath)
    
    def export_markdown(self, report: Dict[str, Any], filename: str = None) -> str:
        """
        Export report to Markdown format
        
        Args:
            report: Report dictionary
            filename: Optional filename
            
        Returns:
            Path to exported file
        """
        if filename is None:
            filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        
        md_content = self._generate_markdown(report)
        
        filepath = self.export_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        return str(filepath)
    
    def _generate_markdown(self, report: Dict[str, Any]) -> str:
        """Generate Markdown content from report"""
        md = f"""# {APP_NAME} - Security Incident Report

## Report Information
- **Report ID:** {report.get('report_metadata', {}).get('report_id', 'N/A')}
- **Generated By:** {APP_NAME} v{APP_VERSION}
- **Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Classification:** CONFIDENTIAL

---

## Executive Summary

### Risk Assessment
- **Risk Score:** {report.get('executive_summary', {}).get('risk_score', 'N/A')}/100
- **Risk Level:** {report.get('executive_summary', {}).get('risk_level', 'N/A')}
- **Total Events Analyzed:** {report.get('executive_summary', {}).get('total_events_analyzed', 0)}

### Key Findings
"""
        for finding in report.get('executive_summary', {}).get('key_findings', []):
            md += f"- {finding}\n"
        
        md += f"""
---

## Technical Findings

| Finding Type | Count | Severity |
|-------------|-------|----------|
"""
        tech_table = report.get('technical_findings', {}).get('summary_table', {})
        for key, value in tech_table.items():
            md += f"| {key.replace('_', ' ').title()} | {value} | - |\n"
        
        md += f"""
---

## Indicators of Compromise

### IP Addresses
"""
        for ip in report.get('indicators_of_compromise', {}).get('ip_addresses', [])[:10]:
            md += f"- `{ip.get('indicator', 'N/A')}`\n"
        
        md += f"""
---

## Recommendations

"""
        for i, rec in enumerate(report.get('recommendations', [])[:5], 1):
            md += f"{i}. {rec}\n"
        
        md += f"""
---

*Report generated by {APP_NAME} v{APP_VERSION} - Confidential SOC Document*
"""
        return md
    
    def export_html(self, report: Dict[str, Any], findings: Dict[str, Any] = None,
                   charts: Dict[str, str] = None, filename: str = None) -> str:
        """
        Export report to HTML format with optional charts
        
        Args:
            report: Report dictionary
            findings: Raw findings for detailed tables
            charts: Dictionary of base64-encoded charts
            filename: Optional filename
            
        Returns:
            Path to exported file
        """
        if filename is None:
            filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        
        html_content = self._generate_html(report, findings, charts)
        
        filepath = self.export_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return str(filepath)
    
    def _generate_html(self, report: Dict[str, Any], findings: Dict[str, Any],
                      charts: Dict[str, str]) -> str:
        """Generate HTML content with professional styling"""
        
        # Get risk color
        risk_score = report.get('executive_summary', {}).get('risk_score', 0)
        if risk_score >= 70:
            risk_color = "#DC3545"
            risk_bg = "#F8D7DA"
        elif risk_score >= 40:
            risk_color = "#FD7E14"
            risk_bg = "#FFF3CD"
        else:
            risk_color = "#28A745"
            risk_bg = "#D4EDDA"
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SOC Incident Report - {report.get('report_metadata', {}).get('report_id', 'N/A')}</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #1e1e1e;
            color: #d4d4d4;
            line-height: 1.6;
            padding: 20px;
        }}
        
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: #252526;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 4px 6px rgba(0,0,0,0.3);
        }}
        
        .header {{
            background: linear-gradient(135deg, #0d47a1 0%, #1a237e 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }}
        
        .header h1 {{
            font-size: 28px;
            margin-bottom: 10px;
        }}
        
        .header .subtitle {{
            opacity: 0.9;
            font-size: 14px;
        }}
        
        .content {{
            padding: 30px;
        }}
        
        .section {{
            margin-bottom: 30px;
            background: #2d2d30;
            border-radius: 8px;
            padding: 20px;
        }}
        
        .section h2 {{
            color: #4fc3f7;
            border-bottom: 2px solid #4fc3f7;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }}
        
        .risk-badge {{
            display: inline-block;
            padding: 8px 16px;
            border-radius: 4px;
            font-weight: bold;
            font-size: 24px;
            background: {risk_color};
            color: white;
        }}
        
        .risk-card {{
            background: {risk_bg};
            color: {risk_color};
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
            text-align: center;
        }}
        
        .metric-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 20px;
        }}
        
        .metric-card {{
            background: #3c3c3c;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            border-left: 4px solid #4fc3f7;
        }}
        
        .metric-value {{
            font-size: 32px;
            font-weight: bold;
            color: #4fc3f7;
        }}
        
        .metric-label {{
            font-size: 12px;
            text-transform: uppercase;
            color: #858585;
            margin-top: 5px;
        }}
        
        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }}
        
        th {{
            background: #3c3c3c;
            padding: 12px;
            text-align: left;
            font-weight: bold;
            color: #4fc3f7;
            border-bottom: 2px solid #4fc3f7;
        }}
        
        td {{
            padding: 10px;
            border-bottom: 1px solid #3c3c3c;
        }}
        
        tr:hover {{
            background: #3c3c3c;
        }}
        
        .finding-critical {{
            color: #f48771;
            font-weight: bold;
        }}
        
        .finding-high {{
            color: #f7a55a;
        }}
        
        .finding-medium {{
            color: #ffd700;
        }}
        
        .footer {{
            background: #1e1e1e;
            padding: 20px;
            text-align: center;
            font-size: 12px;
            color: #858585;
            border-top: 1px solid #3c3c3c;
        }}
        
        .chart-container {{
            margin: 20px 0;
            text-align: center;
        }}
        
        .chart-img {{
            max-width: 100%;
            height: auto;
            border-radius: 8px;
        }}
        
        .badge {{
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 11px;
            font-weight: bold;
        }}
        
        .badge-critical {{ background: #DC3545; color: white; }}
        .badge-high {{ background: #FD7E14; color: white; }}
        .badge-medium {{ background: #FFC107; color: black; }}
        .badge-low {{ background: #28A745; color: white; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🛡️ SOC Incident Investigation Report</h1>
            <div class="subtitle">{self.company_name} | {report.get('report_metadata', {}).get('report_id', 'N/A')}</div>
            <div class="subtitle">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</div>
        </div>
        
        <div class="content">
            <!-- Executive Summary -->
            <div class="section">
                <h2>Executive Summary</h2>
                <div class="risk-card">
                    <div>Overall Risk Score</div>
                    <div class="risk-badge">{risk_score}/100</div>
                    <div style="margin-top: 10px;">{report.get('executive_summary', {}).get('risk_level', 'N/A')}</div>
                </div>
                
                <div class="metric-grid">
                    <div class="metric-card">
                        <div class="metric-value">{report.get('executive_summary', {}).get('total_events_analyzed', 0)}</div>
                        <div class="metric-label">Total Events</div>
                    </div>
                    <div class="metric-card">
                        <div class="metric-value">{report.get('executive_summary', {}).get('critical_findings', 0)}</div>
                        <div class="metric-label">Critical Findings</div>
                    </div>
                    <div class="metric-card">
                        <div class="metric-value">{report.get('executive_summary', {}).get('high_findings', 0)}</div>
                        <div class="metric-label">High Findings</div>
                    </div>
                </div>
                
                <h3>Key Findings</h3>
                <ul>
"""
        for finding in report.get('executive_summary', {}).get('key_findings', []):
            html += f"<li>{finding}</li>\n"
        
        html += f"""
                </ul>
            </div>
            
            <!-- Charts -->
"""
        if charts:
            html += f"""
            <div class="section">
                <h2>Visual Analytics</h2>
"""
            for chart_name, chart_data in charts.items():
                html += f"""
                <div class="chart-container">
                    <img src="data:image/png;base64,{chart_data}" class="chart-img" alt="{chart_name}">
                </div>
"""
            html += f"""
            </div>
"""
        
        # Technical Findings Table
        html += f"""
            <div class="section">
                <h2>Technical Findings Summary</h2>
                <table>
                    <thead>
                        <tr><th>Finding Type</th><th>Count</th></tr>
                    </thead>
                    <tbody>
"""
        tech_table = report.get('technical_findings', {}).get('summary_table', {})
        for key, value in tech_table.items():
            html += f"<tr><td>{key.replace('_', ' ').title()}</td><td>{value}</td></tr>\n"
        
        html += f"""
                    </tbody>
                </table>
            </div>
            
            <!-- Recommendations -->
            <div class="section">
                <h2>Recommendations</h2>
                <ol>
"""
        for rec in report.get('recommendations', [])[:5]:
            html += f"<li>{rec}</li>\n"
        
        html += f"""
                </ol>
            </div>
        </div>
        
        <div class="footer">
            <p>Confidential - SOC Internal Use Only</p>
            <p>Generated by {APP_NAME} v{APP_VERSION}</p>
        </div>
    </div>
</body>
</html>
"""
        return html
    
    def export_excel(self, report: Dict[str, Any], findings_df: pd.DataFrame = None,
                    filename: str = None) -> str:
        """
        Export report to Excel with multiple sheets
        
        Args:
            report: Report dictionary
            findings_df: DataFrame with findings
            filename: Optional filename
            
        Returns:
            Path to exported file
        """
        if not OPENPYXL_AVAILABLE:
            return self.export_csv(findings_df, filename) if findings_df is not None else None
        
        if filename is None:
            filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
        
        filepath = self.export_dir / filename
        
        wb = Workbook()
        
        # Executive Summary sheet
        ws1 = wb.active
        ws1.title = "Executive Summary"
        
        # Add styling
        header_font = Font(bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
        
        # Write summary data
        summary_data = [
            ["Report ID", report.get('report_metadata', {}).get('report_id', 'N/A')],
            ["Generated", datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
            ["Risk Score", report.get('executive_summary', {}).get('risk_score', 'N/A')],
            ["Risk Level", report.get('executive_summary', {}).get('risk_level', 'N/A')],
            ["Total Events", report.get('executive_summary', {}).get('total_events_analyzed', 0)],
            ["Critical Findings", report.get('executive_summary', {}).get('critical_findings', 0)],
            ["High Findings", report.get('executive_summary', {}).get('high_findings', 0)],
        ]
        
        for row, (key, value) in enumerate(summary_data, 1):
            ws1.cell(row=row, column=1, value=key)
            ws1.cell(row=row, column=2, value=value)
        
        # Technical Findings sheet
        ws2 = wb.create_sheet("Technical Findings")
        tech_table = report.get('technical_findings', {}).get('summary_table', {})
        
        headers = ["Finding Type", "Count"]
        for col, header in enumerate(headers, 1):
            cell = ws2.cell(row=1, column=col, value=header)
            cell.font = header_font
            cell.fill = header_fill
        
        for row, (key, value) in enumerate(tech_table.items(), 2):
            ws2.cell(row=row, column=1, value=key.replace('_', ' ').title())
            ws2.cell(row=row, column=2, value=value)
        
        # Adjust column widths
        for ws in wb.worksheets:
            for column in ws.columns:
                max_length = 0
                column_letter = column[0].column_letter
                for cell in column:
                    try:
                        if len(str(cell.value)) > max_length:
                            max_length = len(str(cell.value))
                    except:
                        pass
                adjusted_width = min(max_length + 2, 50)
                ws.column_dimensions[column_letter].width = adjusted_width
        
        # Findings data sheet if provided
        if findings_df is not None:
            ws3 = wb.create_sheet("Detailed Findings")
            for col_idx, col_name in enumerate(findings_df.columns, 1):
                cell = ws3.cell(row=1, column=col_idx, value=str(col_name))
                cell.font = header_font
                cell.fill = header_fill
            
            for row_idx, row in enumerate(findings_df.head(1000).iterrows(), 2):
                for col_idx, value in enumerate(row[1], 1):
                    ws3.cell(row=row_idx, column=col_idx, value=str(value))
        
        wb.save(filepath)
        return str(filepath)
    
    def export_pdf(self, report: Dict[str, Any], findings: Dict[str, Any] = None,
                  charts: Dict[str, str] = None, filename: str = None) -> Optional[str]:
        """
        Export report to PDF (requires WeasyPrint)
        
        Args:
            report: Report dictionary
            findings: Raw findings
            charts: Base64 chart data
            filename: Optional filename
            
        Returns:
            Path to exported file or None if WeasyPrint not available
        """
        if not WEASYPRINT_AVAILABLE:
            # Fallback: generate HTML and notify
            html_path = self.export_html(report, findings, charts, 
                                        filename.replace('.pdf', '.html') if filename else None)
            print(f"WeasyPrint not available. HTML report saved to: {html_path}")
            return None
        
        if filename is None:
            filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        filepath = self.export_dir / filename
        
        # Generate HTML first
        html_content = self._generate_html(report, findings, charts)
        
        # Convert to PDF
        HTML(string=html_content).write_pdf(filepath)
        
        return str(filepath)
    
    def export_all_formats(self, report: Dict[str, Any], findings_df: pd.DataFrame = None,
                          findings: Dict[str, Any] = None, charts: Dict[str, str] = None) -> Dict[str, str]:
        """
        Export report in all available formats
        
        Returns:
            Dictionary of format to file path
        """
        exports = {}
        
        # JSON
        exports['json'] = self.export_json(report)
        
        # Markdown
        exports['markdown'] = self.export_markdown(report)
        
        # HTML
        exports['html'] = self.export_html(report, findings, charts)
        
        # CSV (if findings_df provided)
        if findings_df is not None:
            exports['csv'] = self.export_csv(findings_df)
        
        # Excel (if findings_df provided and openpyxl available)
        if findings_df is not None:
            exports['excel'] = self.export_excel(report, findings_df)
        
        # PDF (attempt)
        pdf_path = self.export_pdf(report, findings, charts)
        if pdf_path:
            exports['pdf'] = pdf_path
        
        return exports


# ============================================
# CONVENIENCE FUNCTIONS
# ============================================

def quick_export(data: Union[Dict, pd.DataFrame], format: str = 'json', 
                filename: str = None) -> str:
    """Quick export helper"""
    exporter = ReportExporter()
    
    if format == 'json' and isinstance(data, dict):
        return exporter.export_json(data, filename)
    elif format == 'csv' and isinstance(data, pd.DataFrame):
        return exporter.export_csv(data, filename)
    elif format == 'markdown' and isinstance(data, dict):
        return exporter.export_markdown(data, filename)
    else:
        raise ValueError(f"Unsupported format {format} for data type {type(data)}")


# ============================================
# TESTING CODE
# ============================================

if __name__ == "__main__":
    print("📤 Testing Exporters Module")
    print("=" * 60)
    
    # Create sample report
    sample_report = {
        'report_metadata': {
            'report_id': 'SOC-IR-20250320-001',
            'generated_by': APP_NAME,
            'version': APP_VERSION
        },
        'executive_summary': {
            'risk_score': 75,
            'risk_level': 'HIGH',
            'total_events_analyzed': 1250,
            'critical_findings': 3,
            'high_findings': 8,
            'key_findings': [
                'Suspicious PowerShell execution detected (5 instances)',
                'Lateral movement indicators found (3 events)',
                'Privilege escalation attempts detected (2 events)'
            ]
        },
        'technical_findings': {
            'summary_table': {
                'failed_logins': 50,
                'suspicious_powershell': 5,
                'privilege_escalation': 3,
                'lateral_movement': 2
            }
        },
        'recommendations': [
            'Enable PowerShell logging and constrained language mode',
            'Implement Multi-Factor Authentication (MFA)',
            'Restrict administrative access using JIT/PAM'
        ],
        'indicators_of_compromise': {
            'ip_addresses': [
                {'indicator': '10.0.2.45', 'type': 'source_ip'},
                {'indicator': '192.168.1.100', 'type': 'source_ip'}
            ]
        }
    }
    
    sample_df = pd.DataFrame({
        'timestamp': pd.date_range('2025-03-20 08:00:00', periods=100, freq='5min'),
        'event_id': [4625, 4624, 4688] * 34,
        'user': ['admin', 'john', 'user1'] * 34,
        'source_ip': ['10.0.2.45', '192.168.1.100', '8.8.8.8'] * 34
    })
    
    exporter = ReportExporter(company_name="ACME Security")
    
    # Test 1: JSON export
    print("\n📋 Test 1: JSON Export")
    json_path = exporter.export_json(sample_report)
    print(f"   Saved to: {json_path}")
    
    # Test 2: Markdown export
    print("\n📋 Test 2: Markdown Export")
    md_path = exporter.export_markdown(sample_report)
    print(f"   Saved to: {md_path}")
    
    # Test 3: HTML export
    print("\n📋 Test 3: HTML Export")
    html_path = exporter.export_html(sample_report)
    print(f"   Saved to: {html_path}")
    
    # Test 4: CSV export
    print("\n📋 Test 4: CSV Export")
    csv_path = exporter.export_csv(sample_df)
    print(f"   Saved to: {csv_path}")
    
    # Test 5: Excel export
    print("\n📋 Test 5: Excel Export")
    excel_path = exporter.export_excel(sample_report, sample_df)
    print(f"   Saved to: {excel_path}")
    
    # Test 6: Export all formats
    print("\n📋 Test 6: Export All Formats")
    all_exports = exporter.export_all_formats(sample_report, sample_df)
    print(f"   Formats exported: {list(all_exports.keys())}")
    for fmt, path in all_exports.items():
        print(f"   - {fmt.upper()}: {Path(path).name}")
    
    print("\n" + "=" * 60)
    print("✅ Exporters Module Ready")
    print(f"\n📁 All exports saved to: {exporter.export_dir}")